name: Main

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - run: cmake -S . -B build && cmake --build build --config Release
      - run: cd build && ctest -C Release